services:
  - type: web
    name: calculator-suite
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: calculator-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: calculator-redis
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
      - key: PYTHONUNBUFFERED
        value: 1

databases:
  - name: calculator-db
    databaseName: calculator_suite
    user: calculator_user
    plan: free

services:
  - type: redis
    name: calculator-redis
    plan: free
    maxmemoryPolicy: allkeys-lru